name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build CronHostedService --configuration Release
    - name: Publish with dotnet
      run: dotnet publish CronHostedService --output artifacts/ --configuration Release
    - name: Pack NuGet Package
      run: dotnet pack CronHostedService --output artifacts/ --configuration Release
    - name: Push package to NuGet
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY}} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CronHostedService
        path: artifacts/
